image: alpine

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

pages:
  stage: deploy
  script:
  - apk update && apk add doxygen graphviz
  - git submodule init && git submodule update
  - doxygen Doxyfile
  - mv doc/html/ public/
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  environment: production